#!/bin/bash

rm temp/*

g++ -c src/functions/*.cpp
g++ -c src/geometry/structuredHexMesh.cpp
g++ -c src/geometry/octreeSHM.cpp
g++ -c src/logs/*.cpp
#g++ -c src/materials/*.cpp
g++ -c src/maths/*.cpp
#g++ -c src/phase/*.cpp
g++ -c main.cpp

g++ -std=c++11 -o main main.o setfun.o structuredHexMesh.o octreeSHM.o log.o vec3.o vec3operations.o 
rm *.o

time ./main

echo inserting headers temp/meshIO...
sed -i '1 i\\x, y, z, level' temp/meshIO_*
zip -r temp.zip temp/
mv temp.zip ~/temp.zip
